### ISSUE TITLE
这 expo打包是真麻烦啊 ,    expo   go能够运行, 本地又不能打包,  云打包特别慢而且还不是apk格式的

### ISSUE THREAD

**Issue by Super1Windcloud** [wengqianshan/WuKongIMReactNative#1]
这 expo打包是真麻烦啊 ,    expo   go能够运行, 本地又不能打包,  云打包特别慢而且还不是apk格式的

**Comment by wengqianshan** [comment]
云打包是很慢，我一般都是本地打包

本地打包需要配置原生环境，Android 可以按照这个文档： https://docs.expo.dev/get-started/set-up-your-environment/?platform=android&device=simulated

环境配好之后打apk 包可以执行这个命令:

```shell
yarn build:android:apk
```

ps: 记得拉取最新代码哈

**Comment by Super1Windcloud** [comment]
无语两个命令都不行,   看来我是不得不投向flutter的阵营了 
>  ![image](https://github.com/user-attachments/assets/cfd4d358-41b4-4510-bd8d-d93d681909d8)

- ## *第二个竟然还报错依赖构建路径重复* 

![image](https://github.com/user-attachments/assets/c4795029-fd5a-4799-911c-1628d7ab24ed)

**Comment by Super1Windcloud** [comment]
wsl 也试了失败, 还是云打包才行, 配置打包成apk格式
